services:
 xolo-db:
  image: mongo:8-noble
  ports:
    - ${XOLO_MONGODB_PORT:-27018}:27017
  volumes:
    - xolo-db:/data/db
    - ./db/mongod.conf:/etc/mongo/mongod.conf:ro

  networks:
    - xolo-net
  restart: unless-stopped
  command: ["mongod", "--config","/etc/mongo/mongod.conf"]
# =============================
# XOLO Cache Service
# =============================
 xolo-cache:
  image: redis:7.0.11-alpine
  ports:
    - ${XOLO_CACHE_REDIS_PORT:-6379}:6379
  volumes:
    - xolo-cache-data:/data
  networks:
    - xolo-net
  restart: unless-stopped

# =============================
# XOLO API Service
# =============================
 xolo:
  image: nachocode/xolo:api-0.0.11a0
  env_file:
    - .env.dev
  # environment:
  ports:
    - ${XOLO_PORT:-10001}:${XOLO_PORT:-10001}
  volumes:
    # - /log:/log
    # - /mictlanx/xolo:/mictlanx/xolo
    - xolo-data:/xolo
  networks:
    - xolo-net
  restart: unless-stopped
  depends_on:
    - xolo-db
  command: uvicorn xoloapi.server:app --host ${XOLO_HOST-0.0.0.0} --port ${XOLO_PORT-10000} ${XOLO_RELOAD+--reload} --log-level debug


networks:
 xolo-net:
  # external: true
volumes:
 xolo-db:
  external: true
 xolo-data:
 xolo-cache-data:
  # external: true
